services:
  - type: web
    name: telegram-schedule-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps
      export PYTHONPATH=$PYTHONPATH:$(pwd)
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /webhook
    autoDeploy: true 